title: Josué Boelter # your name (or website title) here
logo: ""/images/1596144080254.jfif?raw=true"" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/joboelter/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-YHT1R600KD # your Google Analytics tracking ID here
